export {
    MOBILE_FIELD_TYPES,
    applyDecimalNormalization,
    applyInputMask,
    applyOnLoadAutoValues,
    applyOnSubmitAutoValues,
    cellInputValue,
    collectFieldDefaults,
    displayInputValue,
    effectiveInputMaxLength,
    ensureFieldIdentity,
    formatLocalDate,
    getFieldKey,
    hasMeaningfulValue,
    isNavigationalField,
    isOnPlatform,
    normalizeDecimalValue,
    parseFieldDefault,
    parseLocalDate,
    resolveAutoValue,
    resolveAutoValueForField,
    resolveFormLinkParams,
    validateFieldConstraints,
} from '../../../../packages/logic/src/formFields';
export type { FieldIdentity, FieldLike, MobileFieldType } from '../../../../packages/logic/src/formFields';
