import uuid
from typing import Any
from sqlalchemy.orm import Session
from app.services.analytics_service import AnalyticsService

class WalkerComputeService:
    @staticmethod
    def process_payload(db: Session, org_id: uuid.UUID, dataset_id: uuid.UUID, payload: dict[str, Any]) -> list[dict[str, Any]]:
        workflow = payload.get("workflow", [])
        
        filters_map = {"combinator": "and", "rules": []}
        group_by = []
        aggregates = []
        select_fields = []
        order_by = []
        
        for step in workflow:
            step_type = step.get("type")
            if step_type == "filter":
                for f in step.get("filters", []):
                    rule = f.get("rule")
                    if not rule:
                        continue
                    field_key = f.get("fid")
                    rule_type = rule.get("type")
                    val = rule.get("value")
                    
                    if rule_type in ("range", "temporal range"):
                        if isinstance(val, list) and len(val) == 2 and val[0] is not None and val[1] is not None:
                            filters_map["rules"].append({
                                "field": field_key,
                                "operator": "between",
                                "value": f"{val[0]},{val[1]}"
                            })
                    elif rule_type == "one of":
                        if isinstance(val, list) and val:
                            filters_map["rules"].append({
                                "field": field_key,
                                "operator": "in",
                                "value": val
                            })
                    elif rule_type == "not in":
                        if isinstance(val, list) and val:
                            filters_map["rules"].append({
                                "field": field_key,
                                "operator": "notIn",
                                "value": val
                            })
            
            elif step_type == "view":
                queries = step.get("query", [])
                for q in queries:
                    op = q.get("op")
                    if op == "aggregate":
                        for field in q.get("groupBy", []):
                            if field not in group_by:
                                group_by.append(field)
                        for m in q.get("measures", []):
                            gw_agg = m.get("agg")
                            opla_agg = gw_agg
                            if gw_agg == "mean":
                                opla_agg = "avg"
                            elif gw_agg in ("distinct", "count distinct"):
                                opla_agg = "count_distinct"
                            aggregates.append({
                                "field": m.get("field"),
                                "fn": opla_agg,
                                "alias": m.get("asFieldKey")
                            })
                    elif op == "raw":
                        for field in q.get("fields", []):
                            if field not in select_fields:
                                select_fields.append(field)
                        
            elif step_type == "sort":
                sort_dir = "desc" if step.get("sort") == "descending" else "asc"
                for s in step.get("by", []):
                    order_by.append({"field": s, "direction": sort_dir})

        limit = payload.get("limit", 5000)
        offset = payload.get("offset", 0)
        if limit is None or limit > 10000:
            limit = 10000

        final_filters = filters_map if filters_map["rules"] else None

        # Some fields might be generated by transform steps which our mapper currently ignores
        # For a basic v1 computation bridge this covers 80% of usecases
        
        # If we have group by but no aggregates, execute_query might just select the group_by columns.
        # But if it's completely raw, select_fields should be populated.

        result = AnalyticsService.execute_query(
            db=db,
            org_id=org_id,
            dataset_id=dataset_id,
            select_fields=select_fields,
            filters=final_filters,
            group_by=group_by,
            aggregates=aggregates,
            order_by=order_by,
            limit=limit,
            offset=offset
        )
        
        return result["rows"]
